//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OCPB {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OCPB() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.OCPB", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address In Thai.
        /// </summary>
        internal static string AddressInThai {
            get {
                return ResourceManager.GetString("AddressInThai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        internal static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Career.
        /// </summary>
        internal static string Career {
            get {
                return ResourceManager.GetString("Career", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contain letters A-Z, a-z, at least 1 character..
        /// </summary>
        internal static string character_contain {
            get {
                return ResourceManager.GetString("character_contain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are at least 8 characters long and no more than 15 characters..
        /// </summary>
        internal static string character_long {
            get {
                return ResourceManager.GetString("character_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check ID.
        /// </summary>
        internal static string CheckID {
            get {
                return ResourceManager.GetString("CheckID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check Press.
        /// </summary>
        internal static string checkPress {
            get {
                return ResourceManager.GetString("checkPress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditions for edit.
        /// </summary>
        internal static string Condition {
            get {
                return ResourceManager.GetString("Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Condition_cancel {
            get {
                return ResourceManager.GetString("Condition_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        internal static string Condition_ok {
            get {
                return ResourceManager.GetString("Condition_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Condition_Yes {
            get {
                return ResourceManager.GetString("Condition_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm again.
        /// </summary>
        internal static string Confirm_NewPass {
            get {
                return ResourceManager.GetString("Confirm_NewPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm_Save {
            get {
                return ResourceManager.GetString("Confirm_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Address.
        /// </summary>
        internal static string Contact_address {
            get {
                return ResourceManager.GetString("Contact_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continent.
        /// </summary>
        internal static string Continent {
            get {
                return ResourceManager.GetString("Continent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide phone number or phone number.
        /// </summary>
        internal static string CStr {
            get {
                return ResourceManager.GetString("CStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communicate / request forgotten password.
        /// </summary>
        internal static string CStrEm {
            get {
                return ResourceManager.GetString("CStrEm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        internal static string Current_Pass {
            get {
                return ResourceManager.GetString("Current_Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date From.
        /// </summary>
        internal static string DateComeFrom {
            get {
                return ResourceManager.GetString("DateComeFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string DateComeTo {
            get {
                return ResourceManager.GetString("DateComeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        internal static string District {
            get {
                return ResourceManager.GetString("District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        internal static string DoB {
            get {
                return ResourceManager.GetString("DoB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Password.
        /// </summary>
        internal static string Edit_Password {
            get {
                return ResourceManager.GetString("Edit_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        internal static string Edit_Profile {
            get {
                return ResourceManager.GetString("Edit_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        internal static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string female {
            get {
                return ResourceManager.GetString("female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow Complaint.
        /// </summary>
        internal static string follow_complaint {
            get {
                return ResourceManager.GetString("follow_complaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreigner.
        /// </summary>
        internal static string Foreigner {
            get {
                return ResourceManager.GetString("Foreigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        internal static string forgot_pass {
            get {
                return ResourceManager.GetString("forgot_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identification Number.
        /// </summary>
        internal static string IdentityID {
            get {
                return ResourceManager.GetString("IdentityID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity/Passport.
        /// </summary>
        internal static string IdentityID_or_passport {
            get {
                return ResourceManager.GetString("IdentityID_or_passport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login or.
        /// </summary>
        internal static string label1_layout {
            get {
                return ResourceManager.GetString("label1_layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string label1_register {
            get {
                return ResourceManager.GetString("label1_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office of the Consumer Protection Board B Bldg. 5th Fl, The Government Complex Commemorating his Majesty the King’s 80th Birthday Anniversary, Chaengwattana Rd., Thung song hong Sub-district, Laksi Bangkok, THAILAND. 10210.
        /// </summary>
        internal static string label_footer {
            get {
                return ResourceManager.GetString("label_footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ONLINE MANUAL.
        /// </summary>
        internal static string label_manual {
            get {
                return ResourceManager.GetString("label_manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        internal static string label_Signin {
            get {
                return ResourceManager.GetString("label_Signin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Complaint.
        /// </summary>
        internal static string list_complaint {
            get {
                return ResourceManager.GetString("list_complaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login using your passport number.
        /// </summary>
        internal static string loginwithPass {
            get {
                return ResourceManager.GetString("loginwithPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        internal static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string male {
            get {
                return ResourceManager.GetString("male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        internal static string MobNum {
            get {
                return ResourceManager.GetString("MobNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Complaint.
        /// </summary>
        internal static string my_complaint {
            get {
                return ResourceManager.GetString("my_complaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Title.
        /// </summary>
        internal static string NameTitle {
            get {
                return ResourceManager.GetString("NameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        internal static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        internal static string NewPass {
            get {
                return ResourceManager.GetString("NewPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does not support characters such as +, -..
        /// </summary>
        internal static string not_support {
            get {
                return ResourceManager.GetString("not_support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string number {
            get {
                return ResourceManager.GetString("number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0-9 contain at least 1 letter..
        /// </summary>
        internal static string num_contain {
            get {
                return ResourceManager.GetString("num_contain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaint Online.
        /// </summary>
        internal static string online_complaint {
            get {
                return ResourceManager.GetString("online_complaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oversea Address (In your country).
        /// </summary>
        internal static string OverseaAddress {
            get {
                return ResourceManager.GetString("OverseaAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string OverseaCity {
            get {
                return ResourceManager.GetString("OverseaCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax No..
        /// </summary>
        internal static string OverseaFaxNo {
            get {
                return ResourceManager.GetString("OverseaFaxNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile No..
        /// </summary>
        internal static string OverseaMobileNo {
            get {
                return ResourceManager.GetString("OverseaMobileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postcode.
        /// </summary>
        internal static string OverseaPostcode {
            get {
                return ResourceManager.GetString("OverseaPostcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone No..
        /// </summary>
        internal static string OverseaTelephoneNo {
            get {
                return ResourceManager.GetString("OverseaTelephoneNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to passport.
        /// </summary>
        internal static string passport {
            get {
                return ResourceManager.GetString("passport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password will be sent to registered email.
        /// </summary>
        internal static string PassSendtoEmail {
            get {
                return ResourceManager.GetString("PassSendtoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postcode.
        /// </summary>
        internal static string Postcode {
            get {
                return ResourceManager.GetString("Postcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string product {
            get {
                return ResourceManager.GetString("product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province.
        /// </summary>
        internal static string Province {
            get {
                return ResourceManager.GetString("Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose of staying in Thailand.
        /// </summary>
        internal static string PurposeToThai {
            get {
                return ResourceManager.GetString("PurposeToThai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real Estate.
        /// </summary>
        internal static string Real_Estate {
            get {
                return ResourceManager.GetString("Real_Estate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you can not access the system. Please reset password.
        /// </summary>
        internal static string ResetAnewPass {
            get {
                return ResourceManager.GetString("ResetAnewPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary.
        /// </summary>
        internal static string Salary {
            get {
                return ResourceManager.GetString("Salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary per month.
        /// </summary>
        internal static string Salarypm {
            get {
                return ResourceManager.GetString("Salarypm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Select Please--.
        /// </summary>
        internal static string Select_dropdown {
            get {
                return ResourceManager.GetString("Select_dropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        internal static string service {
            get {
                return ResourceManager.GetString("service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        internal static string setting {
            get {
                return ResourceManager.GetString("setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex.
        /// </summary>
        internal static string Sex {
            get {
                return ResourceManager.GetString("Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        internal static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ext.
        /// </summary>
        internal static string Telext {
            get {
                return ResourceManager.GetString("Telext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell Clue.
        /// </summary>
        internal static string tell_clue {
            get {
                return ResourceManager.GetString("tell_clue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        internal static string tel_nember {
            get {
                return ResourceManager.GetString("tel_nember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thai.
        /// </summary>
        internal static string Thai {
            get {
                return ResourceManager.GetString("Thai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic.
        /// </summary>
        internal static string Topic {
            get {
                return ResourceManager.GetString("Topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Date.
        /// </summary>
        internal static string TotalDateCome {
            get {
                return ResourceManager.GetString("TotalDateCome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the Login ID..
        /// </summary>
        internal static string UseIden {
            get {
                return ResourceManager.GetString("UseIden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User manual.
        /// </summary>
        internal static string User_manual {
            get {
                return ResourceManager.GetString("User_manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to verify.
        /// </summary>
        internal static string verify {
            get {
                return ResourceManager.GetString("verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string _Username {
            get {
                return ResourceManager.GetString("_Username", resourceCulture);
            }
        }
    }
}
